cask "hyprspace" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.4.0'
  sha256 "6919a75e3aa83a0b5f9d5076edf0df08a333d79d7f25c76220c42bd0bbb818e6"

  url "https://github.com/BarutSRB/HyprSpace/releases/download/v#{version}/HyprSpace-v#{version}.zip"
  name "HyprSpace"
  desc "HyprSpace is a heavily enhanced fork of AeroSpace with centered workspace bar and dwindle layout"
  homepage "https://github.com/BarutSRB/HyprSpace"
  conflicts_with cask: 'hyprspace-dev'

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "xattr -d com.apple.quarantine #{staged_path}/HyprSpace-v#{version}/bin/hyprspace"
    system "xattr -d com.apple.quarantine #{appdir}/HyprSpace.app"
  end

  app "HyprSpace-v#{version}/HyprSpace.app"
  binary "HyprSpace-v#{version}/bin/hyprspace"

  binary "HyprSpace-v#{version}/shell-completion/zsh/_aerospace",
      target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_hyprspace"
  binary "HyprSpace-v#{version}/shell-completion/bash/aerospace",
      target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/hyprspace"
  binary "HyprSpace-v#{version}/shell-completion/fish/aerospace.fish",
      target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/hyprspace.fish"

  Dir["#{staged_path}/HyprSpace-v#{version}/manpage/*"].each { |man| manpage man }
end
