cask "hyprspace" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '0.2.1'
  sha256 "a2be354b68f01154949e33930fa7c0feabc6ba81c93f486fa4655a6b52271503"

  url "file:///Users/barut/Projects/WM/HyprSpace/.release/HyprSpace-v#{version}.zip"
  name "HyprSpace"
  desc "HyprSpace is a heavily enhanced fork of AeroSpace with centered workspace bar and dwindle layout"
  homepage "https://github.com/BarutSRB/HyprSpace"
  conflicts_with cask: 'hyprspace-dev'

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "xattr -d com.apple.quarantine #{staged_path}/HyprSpace-v#{version}/bin/hyprspace"
    system "xattr -d com.apple.quarantine #{appdir}/HyprSpace.app"
  end

  app "HyprSpace-v#{version}/HyprSpace.app"
  binary "HyprSpace-v#{version}/bin/hyprspace"

  binary "HyprSpace-v#{version}/shell-completion/zsh/_hyprspace",
      target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_hyprspace"
  binary "HyprSpace-v#{version}/shell-completion/bash/hyprspace",
      target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/hyprspace"
  binary "HyprSpace-v#{version}/shell-completion/fish/hyprspace.fish",
      target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/hyprspace.fish"

  Dir["#{staged_path}/HyprSpace-v#{version}/manpage/*"].each { |man| manpage man }
end
